{% set name = "capcruncher" %}
{% set version = "0.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/capcruncher-{{ version }}.tar.gz
  sha256: 36298dc04c9af6153d59cb478aa53b2d9677dcb8711edc7db43066da7aa86ac0

build:
  number: 0
  noarch: python
  entry_points:
    - capcruncher = capcruncher.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools
  run:
    - bedtools
    - bowtie2 >=2.4.4
    - click <=8.1.0
    - cooler
    - fastqc
    - flash
    - ibis-framework >=6.0.0
    - iced
    - joblib
    - multiqc
    - more-itertools
    - loguru
    - numpy <=1.23
    - papermill
    - pandas <=2.0.1
    - pip <=22.2.2
    - plotly >5.0.0, <=5.15.0
    - pyarrow >8.0.0, <=9.0.0
    - pybedtools
    - pyranges
    - pysam >0.15.0, <=0.19.1
    - python-duckdb
    - python-xxhash
    - python >=3.10, <3.11
    - ray-core >=2.6.0
    - samtools
    - seaborn
    - setuptools >50.1.0, <=65.0.1
    - snakemake <=7.30.2
    - tqdm
    - trackhub
    - trim-galore
    - ucsc-bedgraphtobigwig
    - ucsc-bedtobigbed
    - ucsc-fetchchromsizes
    - ujson
    - quarto
test:
  imports:
    - capcruncher
    - capcruncher.cli
    - capcruncher.api
  commands:
    - pip check
    - capcruncher --help
  requires:
    - pip

about:
  home: https://github.com/sims-lab/CapCruncher.git
  summary: An end-to-end solution for processing Capture-C, Tri-C and Tiled-C data
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asmith