{% set version = "0.1.3" %}

package:
  name: elastic-blast
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/e/elastic-blast/elastic-blast-{{ version }}.tar.gz
  sha256: 88dead1dca77dcc701859888b5a0fc1e4b2043248de9e441eefcde8e63999c35

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
    - google-cloud-sdk
    - awscli
  run:
    - python >=3.7
    - awscli
    - google-cloud-sdk

test:
  commands:
    - elastic-blast

about:
  home: https://pypi.org/project/elastic-blast/
  license: Public Domain
  license_family: PUBLIC-DOMAIN
  license_file: LICENSE
  summary: "ElasticBLAST is a cloud-based tool to perform your BLAST searches faster and make you more effective."
  dev_url: https://github.com/ncbi/elastic-blast/

extra:
  recipe-maintainers:
    - r78v10a07
